version: '3'
services:
  mysql:
    image: mysql:5.6
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - server

  api:
    image: node:12
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm run start
    networks:
      - server
    depends_on:
      - mysql

networks:
  server:

volumes:
  mysqldata:
